In [1]:
import numpy as np

In [5]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,1,1,0]]).T
Y

array([[0],
       [1],
       [1],
       [0]])

In [3]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [4]:
def dsig(z):
    return sig(z)*(1 - sig(z))

In [26]:
wh = 2 * np.random.random((2,2)) - 1
bh = np.random.random((1, 2))* 2 - 1
wo = 2 * np.random.random((2,1)) - 1
bo = np.random.random(1)* 2 - 1

In [14]:
def forward(x, wh, wo, bh, bo):
    output0 = x
    hidden_layer_input = np.dot(output0, wh) + bh
    hidden_layer_output = sig(hidden_layer_input)
    
    output_layer_input = np.dot(hidden_layer_output, wo) + bo
    output = sig(output_layer_input)
    return output

In [15]:
def train(X, Y, wh, wo, bh, bo, iterations, lr):
    for i in range(iterations):
        output0 = X
        hidden_layer_input = np.dot(output0, wh) + bh
        hidden_layer_output = sig(hidden_layer_input)

        output_layer_input = np.dot(hidden_layer_output, wo) + bo
        output = sig(output_layer_input)

        first_term_output = output - Y
        second_term_output = dsig(output_layer_input)
        first_two_terms_output = first_term_output * second_term_output

        second_term_hidden_layer = dsig(hidden_layer_input)
        first_term_hidden_layer = np.dot(first_two_terms_output, wo.T)
        first_two_terms_hidden = first_term_hidden_layer*second_term_hidden_layer

        changes_wo = np.dot(hidden_layer_output.T, first_two_terms_output)
        changes_wh = np.dot(output0.T, first_two_terms_hidden)

        wh = wh - lr * changes_wh
        wo = wo - lr * changes_wo

        changes_bh = np.sum(first_two_terms_hidden, axis = 0)
        changes_bo = np.sum(first_two_terms_output, axis = 0)

        bh = bh - lr * changes_bh
        bo = bo - lr*changes_bo
    return wh, wo, bh, bo
        

In [27]:
wh, wo, bh, bo = train(X, Y, wh, wo, bh, bo, 100000, 0.1)

In [28]:
forward(X, wh, wo, bh, bo)

array([[ 0.01268594],
       [ 0.98909117],
       [ 0.98898829],
       [ 0.01148253]])

In [29]:
wh

array([[-6.63931523,  5.86076933],
       [ 6.56184516, -6.11030544]])

In [30]:
bh

array([[-3.64544069, -3.23846378]])

In [31]:
wo

array([[ 10.01408509],
       [ 10.18030576]])

In [32]:
bo

array([-4.99354899])